### PR TITLE
Make Windows-compatible

### LINKED ISSUE #41: Windows version
As discussed in person, a Windows version would be great as well (both for users and devs). This requires Unix's pthread library to be either adapted or replaced.

### PR DESCRIPTION
**Pull request by CHrlS98**
PR to make the application Windows-compatible.
With the (very ugly) changes here, I've been able to get the code to compile on Windows. The `pthread` library does not seem to be a problem right now. However the application crashes when loading a `.nii.gz` image. I think it has to do with the compression library `zlib`, installed on Ubuntu by default (I think), but not on Windows. I managed to install it using `vcpkg` (hence the 3000+ files in the PR, which I'll remove once I'm able to visualize something) but the image loading always gives me NULL images.

TODO
* [x] Test with non-compressed nifti `.nii` image;
* [x] Remove `vcpkg` from PR; only add zlib to `deps`;
* [x] Get image loading to work properly.

Will close #41. 

[EDIT] All problem are fixed.

### CODE REVIEW

**Comment by CHrlS98** [comment]
Won't compile anymore after latest commit but that's ok. Almost there for `zlib`. Just need to add the actual library and not just the header file.

**Comment by chamberm** [comment]
From Fibernavigator, (since it runs on Windows) in case this is useful at all: 
https://github.com/scilus/fibernavigator/search?q=zlib

**Comment by CHrlS98** [comment]
@chamberm
Builds and runs on my end! Shaders and icons are correctly copied to build directory.

**Comment by CHrlS98** [comment]
@chamberm
About our latest problem. I've got a working theory. The access violation actually comes from the `glNamedStringARB` function itself. I reproduced the bug by calling the function before calling `gladLoadGLLoader` (application.cpp l. 74). Is it possible your graphics card driver is out of date?

**Comment by chamberm** [comment]
> @chamberm About our latest problem. I've got a working theory. The access violation actually comes from the `glNamedStringARB` function itself. I reproduced the bug by calling the function before calling `gladLoadGLLoader` (application.cpp l. 74). Is it possible your graphics card driver is out of date?

Good point. I updated the drivers , but still having the same problem. Maybe because this is a integrated Intel graphics - it would probably run on my desktop at home with a recent NVIDIA card.

IN any case here is a screenshot of the laptop specs:
image

**Comment by CHrlS98** [comment]
With latest commit, the app should return an error message if it fails to load `glNamedStringARB`. I tested by forcing my graphics card to my integrated Intel UHD Graphics, and the error message shows. It'd seem the problem indeed comes from the Intel dedicated graphics card.

**Comment by AlexVCaron** [comment]
I tested extensively, easily built with VSCode and/or VStudio, no problems running it on the Nvidia GPU. I have the same problem running the program on integrated AMD graphics, it is supposed to support ARB shading, but in reality doesn't from what I saw on the web.

It could be good to leave a note for less tech savvy users about that, and how to configure Windows default GPU for the application, since Win10 takes care of GPU dispatching, which mostly defaults to integrated graphics.

**Comment by CHrlS98** [comment]
Awesome, thanks a lot @AlexVCaron !

The readme is getting pretty dense so I might draft a new PR for documentation using gh-pages containing additional help for installation/setup.

**Comment by CHrlS98** [comment]
@chamberm 
Alright, I think it's safe to say that we now have a working Windows version. I'll go ahead with the merge. About the wiki/documentation, definitely something to keep in mind. I've never used github wiki, but it is an option I can enable from the repo settings. I'll open an issue asking for documentation just to keep a trace.

**Pull request merged**
